In [1]:
import pandas as pd

In [2]:
tickets ={
    "id_ticket": [1001,1002,1003,1004]
    "articulo": ["paracetamol","cafe americano", "ibuprofeno", "agua"],
    "categoria": ["medicamento","cafe","medicamento","bebida"]
    "cantidad": [2,1,1,3]
    "precio_unitario": [25.50,18.0,35.0,15.0]
        }
df=pd.DataFrame(tickets)
print(df)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3699132316.py, line 2)

In [2]:
tickets ={
    "id_ticket": [1001,1002,1003,1004]
    "articulo": ["paracetamol","cafe americano", "ibuprofeno", "agua"],
    "categoria": ["medicamento","cafe","medicamento","bebida"]
    "cantidad": [2,1,1,3]
    "precio_unitario": [25.50,18.0,35.0,15.0]
        }
df=pd.DataFrame(tickets)
print(df)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3699132316.py, line 2)

In [4]:
tickets ={
    "id_ticket": [1001,1002,1003,1004],
    "articulo": ["paracetamol","cafe americano", "ibuprofeno", "agua"],
    "categoria": ["medicamento","cafe","medicamento","bebida"],
    "cantidad": [2,1,1,3],
    "precio_unitario": [25.50,18.0,35.0,15.0]
        }
df=pd.DataFrame(tickets)
print(df)

   id_ticket        articulo    categoria  cantidad  precio_unitario
0       1001     paracetamol  medicamento         2             25.5
1       1002  cafe americano         cafe         1             18.0
2       1003      ibuprofeno  medicamento         1             35.0
3       1004            agua       bebida         3             15.0

In [5]:
df.head()

   id_ticket        articulo    categoria  cantidad  precio_unitario
0       1001     paracetamol  medicamento         2             25.5
1       1002  cafe americano         cafe         1             18.0
2       1003      ibuprofeno  medicamento         1             35.0
3       1004            agua       bebida         3             15.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_ticket        4 non-null      int64
 1   articulo         4 non-null      str
 2   categoria        4 non-null      str
 3   cantidad         4 non-null      int64
 4   precio_unitario  4 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 292.0 bytes

In [7]:
df.describe()

         id_ticket  cantidad  precio_unitario
count     4.000000  4.000000         4.000000
mean   1002.500000  1.750000        23.375000
std       1.290994  0.957427         8.919781
min    1001.000000  1.000000        15.000000
25%    1001.750000  1.000000        17.250000
50%    1002.500000  1.500000        21.750000
75%    1003.250000  2.250000        27.875000
max    1004.000000  3.000000        35.000000

In [8]:
df[total]=df["cantidad"] * df ["precio_unitario"]

NameError: name 'total' is not defined

In [9]:
df["total"]=df["cantidad"]*df["precio_unitario"]
print [df]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [10]:
df["total"]=df["cantidad"]*df["precio_unitario"]
print[df]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [11]:
df["total"]=df["cantidad"]*["precio_unitario"]

ValueError: Lengths of operands do not match: 1 != 4

In [12]:
df["total"]=df["cantidad"]*df["precio_unitario"]

In [13]:
print(df)

   id_ticket        articulo    categoria  cantidad  precio_unitario  total
0       1001     paracetamol  medicamento         2             25.5   51.0
1       1002  cafe americano         cafe         1             18.0   18.0
2       1003      ibuprofeno  medicamento         1             35.0   35.0
3       1004            agua       bebida         3             15.0   45.0

In [14]:
medicamentos=df[df["categoria"]=="medicamento"]

In [15]:
print (medicamento)

NameError: name 'medicamento' is not defined

In [16]:
print (medicamentos)

   id_ticket     articulo    categoria  cantidad  precio_unitario  total
0       1001  paracetamol  medicamento         2             25.5   51.0
2       1003   ibuprofeno  medicamento         1             35.0   35.0

In [17]:
print(df[df["categoria"]== "medicamento"])

   id_ticket     articulo    categoria  cantidad  precio_unitario  total
0       1001  paracetamol  medicamento         2             25.5   51.0
2       1003   ibuprofeno  medicamento         1             35.0   35.0

In [18]:
df[df["total"]>30]

   id_ticket     articulo    categoria  cantidad  precio_unitario  total
0       1001  paracetamol  medicamento         2             25.5   51.0
2       1003   ibuprofeno  medicamento         1             35.0   35.0
3       1004         agua       bebida         3             15.0   45.0

In [19]:
df[df["categoria"}isin(["medicamento","bebida"])]

SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' (954761611.py, line 1)

In [20]:
df[df["categoria"].isin(["medicamento","bebida"])]

   id_ticket     articulo    categoria  cantidad  precio_unitario  total
0       1001  paracetamol  medicamento         2             25.5   51.0
2       1003   ibuprofeno  medicamento         1             35.0   35.0
3       1004         agua       bebida         3             15.0   45.0

In [21]:
df[(df["categoria"}=="medicamento") & (df["cantidad"]>1]

SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' (232047366.py, line 1)

In [22]:
df[(df["categoria"]=="medicamento") & (df["cantidad"] > 1)]

   id_ticket     articulo    categoria  cantidad  precio_unitario  total
0       1001  paracetamol  medicamento         2             25.5   51.0

In [23]:
df.groupby("categoria")["total"].sum()

categoria
bebida         45.0
cafe           18.0
medicamento    86.0
Name: total, dtype: float64

In [24]:
df.groupby("categoria")["total"].mean()

categoria
bebida         45.0
cafe           18.0
medicamento    43.0
Name: total, dtype: float64

In [25]:
df.groupby("categoria")["total"].count()

categoria
bebida         1
cafe           1
medicamento    2
Name: total, dtype: int64

In [26]:
df.groupby("categoria")["total"].max()

categoria
bebida         45.0
cafe           18.0
medicamento    51.0
Name: total, dtype: float64

In [27]:
df.groupby("categoria")["total"].agg(["sum", "mean", "count", "max"])

              sum  mean  count   max
categoria
bebida       45.0  45.0      1  45.0
cafe         18.0  18.0      1  18.0
medicamento  86.0  43.0      2  51.0